import { Question } from './gradeQuestions';
import { Language } from '@/contexts/LanguageContext';

// Translated questions by language for grades 1-5 (most relevant for early detection)
// Higher grades use English as standard academic language

interface TranslatedQuestion extends Question {
  translations: {
    [key in Language]: {
      text: string;
      expectedAnswer: string;
    };
  };
}

// Hindi translations for dyslexia assessment
const dyslexiaQuestionsHindi: Record<number, TranslatedQuestion[]> = {
  1: [
    { id: 1, text: 'Say the word: "CAT"', expectedAnswer: 'cat', type: 'word', translations: { en: { text: 'Say the word: "CAT"', expectedAnswer: 'cat' }, hi: { text: 'यह शब्द बोलो: "बिल्ली"', expectedAnswer: 'बिल्ली' }, pa: { text: 'ਇਹ ਸ਼ਬਦ ਬੋਲੋ: "ਬਿੱਲੀ"', expectedAnswer: 'ਬਿੱਲੀ' }, ta: { text: 'இந்த வார்த்தையைச் சொல்லுங்கள்: "பூனை"', expectedAnswer: 'பூனை' }, te: { text: 'ఈ పదం చెప్పండి: "పిల్లి"', expectedAnswer: 'పిల్లి' } } },
    { id: 2, text: 'Say the word: "DOG"', expectedAnswer: 'dog', type: 'word', translations: { en: { text: 'Say the word: "DOG"', expectedAnswer: 'dog' }, hi: { text: 'यह शब्द बोलो: "कुत्ता"', expectedAnswer: 'कुत्ता' }, pa: { text: 'ਇਹ ਸ਼ਬਦ ਬੋਲੋ: "ਕੁੱਤਾ"', expectedAnswer: 'ਕੁੱਤਾ' }, ta: { text: 'இந்த வார்த்தையைச் சொல்லுங்கள்: "நாய்"', expectedAnswer: 'நாய்' }, te: { text: 'ఈ పదం చెప్పండి: "కుక్క"', expectedAnswer: 'కుక్క' } } },
    { id: 3, text: 'What sound does "B" make?', expectedAnswer: 'buh', type: 'phoneme', translations: { en: { text: 'What sound does "B" make?', expectedAnswer: 'buh' }, hi: { text: '"ब" की ध्वनि क्या है?', expectedAnswer: 'ब' }, pa: { text: '"ਬ" ਦੀ ਆਵਾਜ਼ ਕੀ ਹੈ?', expectedAnswer: 'ਬ' }, ta: { text: '"ப" எந்த ஒலி எழுப்புகிறது?', expectedAnswer: 'ப' }, te: { text: '"బ" ఏ ధ్వని చేస్తుంది?', expectedAnswer: 'బ' } } },
    { id: 4, text: 'Say the word: "SUN"', expectedAnswer: 'sun', type: 'word', translations: { en: { text: 'Say the word: "SUN"', expectedAnswer: 'sun' }, hi: { text: 'यह शब्द बोलो: "सूरज"', expectedAnswer: 'सूरज' }, pa: { text: 'ਇਹ ਸ਼ਬਦ ਬੋਲੋ: "ਸੂਰਜ"', expectedAnswer: 'ਸੂਰਜ' }, ta: { text: 'இந்த வார்த்தையைச் சொல்லுங்கள்: "சூரியன்"', expectedAnswer: 'சூரியன்' }, te: { text: 'ఈ పదం చెప్పండి: "సూర్యుడు"', expectedAnswer: 'సూర్యుడు' } } },
    { id: 5, text: 'Say the letters: A, B, C', expectedAnswer: 'a b c', type: 'phoneme', translations: { en: { text: 'Say the letters: A, B, C', expectedAnswer: 'a b c' }, hi: { text: 'ये अक्षर बोलो: अ, आ, इ', expectedAnswer: 'अ आ इ' }, pa: { text: 'ਇਹ ਅੱਖਰ ਬੋਲੋ: ਅ, ਆ, ਇ', expectedAnswer: 'ਅ ਆ ਇ' }, ta: { text: 'இந்த எழுத்துகளைச் சொல்லுங்கள்: அ, ஆ, இ', expectedAnswer: 'அ ஆ இ' }, te: { text: 'ఈ అక్షరాలు చెప్పండి: అ, ఆ, ఇ', expectedAnswer: 'అ ఆ ఇ' } } },
    { id: 6, text: 'What rhymes with "CAT"?', expectedAnswer: 'bat hat mat', type: 'phoneme', translations: { en: { text: 'What rhymes with "CAT"?', expectedAnswer: 'bat hat mat' }, hi: { text: '"मात" के साथ क्या तुकबंदी करता है?', expectedAnswer: 'बात रात खात' }, pa: { text: '"ਮਾਂ" ਨਾਲ ਕੀ ਤੁਕਬੰਦੀ ਕਰਦਾ ਹੈ?', expectedAnswer: 'ਕਾਂ ਨਾਂ' }, ta: { text: '"பூ" உடன் என்ன ஒலிக்கும்?', expectedAnswer: 'கூ தூ மூ' }, te: { text: '"మా" తో ఏది ప్రాస కలుస్తుంది?', expectedAnswer: 'కా నా తా' } } },
    { id: 7, text: 'Say the word: "RED"', expectedAnswer: 'red', type: 'word', translations: { en: { text: 'Say the word: "RED"', expectedAnswer: 'red' }, hi: { text: 'यह शब्द बोलो: "लाल"', expectedAnswer: 'लाल' }, pa: { text: 'ਇਹ ਸ਼ਬਦ ਬੋਲੋ: "ਲਾਲ"', expectedAnswer: 'ਲਾਲ' }, ta: { text: 'இந்த வார்த்தையைச் சொல்லுங்கள்: "சிவப்பு"', expectedAnswer: 'சிவப்பு' }, te: { text: 'ఈ పదం చెప్పండి: "ఎరుపు"', expectedAnswer: 'ఎరుపు' } } },
    { id: 8, text: 'Read: "I see a dog"', expectedAnswer: 'i see a dog', type: 'sentence', translations: { en: { text: 'Read: "I see a dog"', expectedAnswer: 'i see a dog' }, hi: { text: 'पढ़ो: "मुझे एक कुत्ता दिखता है"', expectedAnswer: 'मुझे एक कुत्ता दिखता है' }, pa: { text: 'ਪੜ੍ਹੋ: "ਮੈਨੂੰ ਇੱਕ ਕੁੱਤਾ ਦਿਖਦਾ ਹੈ"', expectedAnswer: 'ਮੈਨੂੰ ਇੱਕ ਕੁੱਤਾ ਦਿਖਦਾ ਹੈ' }, ta: { text: 'படிக்கவும்: "நான் ஒரு நாயைப் பார்க்கிறேன்"', expectedAnswer: 'நான் ஒரு நாயைப் பார்க்கிறேன்' }, te: { text: 'చదవండి: "నాకు ఒక కుక్క కనిపిస్తోంది"', expectedAnswer: 'నాకు ఒక కుక్క కనిపిస్తోంది' } } },
  ],
  2: [
    { id: 1, text: 'Say the word: "APPLE"', expectedAnswer: 'apple', type: 'word', translations: { en: { text: 'Say the word: "APPLE"', expectedAnswer: 'apple' }, hi: { text: 'यह शब्द बोलो: "सेब"', expectedAnswer: 'सेब' }, pa: { text: 'ਇਹ ਸ਼ਬਦ ਬੋਲੋ: "ਸੇਬ"', expectedAnswer: 'ਸੇਬ' }, ta: { text: 'இந்த வார்த்தையைச் சொல்லுங்கள்: "ஆப்பிள்"', expectedAnswer: 'ஆப்பிள்' }, te: { text: 'ఈ పదం చెప్పండి: "ఆపిల్"', expectedAnswer: 'ఆపిల్' } } },
    { id: 2, text: 'Say the word: "HAPPY"', expectedAnswer: 'happy', type: 'word', translations: { en: { text: 'Say the word: "HAPPY"', expectedAnswer: 'happy' }, hi: { text: 'यह शब्द बोलो: "खुश"', expectedAnswer: 'खुश' }, pa: { text: 'ਇਹ ਸ਼ਬਦ ਬੋਲੋ: "ਖੁਸ਼"', expectedAnswer: 'ਖੁਸ਼' }, ta: { text: 'இந்த வார்த்தையைச் சொல்லுங்கள்: "மகிழ்ச்சி"', expectedAnswer: 'மகிழ்ச்சி' }, te: { text: 'ఈ పదం చెప్పండి: "సంతోషం"', expectedAnswer: 'సంతోషం' } } },
    { id: 3, text: 'Say the sounds in "STOP" (S-T-O-P)', expectedAnswer: 's t o p', type: 'phoneme', translations: { en: { text: 'Say the sounds in "STOP" (S-T-O-P)', expectedAnswer: 's t o p' }, hi: { text: '"रुको" में ध्वनियाँ बोलो', expectedAnswer: 'र उ क ओ' }, pa: { text: '"ਰੁਕੋ" ਵਿੱਚ ਆਵਾਜ਼ਾਂ ਬੋਲੋ', expectedAnswer: 'ਰ ਉ ਕ ਓ' }, ta: { text: '"நில்" என்பதில் ஒலிகளைச் சொல்லுங்கள்', expectedAnswer: 'நி ல்' }, te: { text: '"ఆగు" లో ధ్వనులు చెప్పండి', expectedAnswer: 'ఆ గు' } } },
    { id: 4, text: 'Read: "The cat is big"', expectedAnswer: 'the cat is big', type: 'sentence', translations: { en: { text: 'Read: "The cat is big"', expectedAnswer: 'the cat is big' }, hi: { text: 'पढ़ो: "बिल्ली बड़ी है"', expectedAnswer: 'बिल्ली बड़ी है' }, pa: { text: 'ਪੜ੍ਹੋ: "ਬਿੱਲੀ ਵੱਡੀ ਹੈ"', expectedAnswer: 'ਬਿੱਲੀ ਵੱਡੀ ਹੈ' }, ta: { text: 'படிக்கவும்: "பூனை பெரியது"', expectedAnswer: 'பூனை பெரியது' }, te: { text: 'చదవండి: "పిల్లి పెద్దది"', expectedAnswer: 'పిల్లి పెద్దది' } } },
    { id: 5, text: 'Say the word: "YELLOW"', expectedAnswer: 'yellow', type: 'word', translations: { en: { text: 'Say the word: "YELLOW"', expectedAnswer: 'yellow' }, hi: { text: 'यह शब्द बोलो: "पीला"', expectedAnswer: 'पीला' }, pa: { text: 'ਇਹ ਸ਼ਬਦ ਬੋਲੋ: "ਪੀਲਾ"', expectedAnswer: 'ਪੀਲਾ' }, ta: { text: 'இந்த வார்த்தையைச் சொல்லுங்கள்: "மஞ்சள்"', expectedAnswer: 'மஞ்சள்' }, te: { text: 'ఈ పదం చెప్పండి: "పసుపు"', expectedAnswer: 'పసుపు' } } },
    { id: 6, text: 'What sound does "PH" make?', expectedAnswer: 'f', type: 'phoneme', translations: { en: { text: 'What sound does "PH" make?', expectedAnswer: 'f' }, hi: { text: '"फ" की ध्वनि क्या है?', expectedAnswer: 'फ' }, pa: { text: '"ਫ" ਦੀ ਆਵਾਜ਼ ਕੀ ਹੈ?', expectedAnswer: 'ਫ' }, ta: { text: '"ப" எந்த ஒலி?', expectedAnswer: 'ப' }, te: { text: '"ఫ" ఏ ధ్వని?', expectedAnswer: 'ఫ' } } },
    { id: 7, text: 'Say the word: "FRIEND"', expectedAnswer: 'friend', type: 'word', translations: { en: { text: 'Say the word: "FRIEND"', expectedAnswer: 'friend' }, hi: { text: 'यह शब्द बोलो: "दोस्त"', expectedAnswer: 'दोस्त' }, pa: { text: 'ਇਹ ਸ਼ਬਦ ਬੋਲੋ: "ਦੋਸਤ"', expectedAnswer: 'ਦੋਸਤ' }, ta: { text: 'இந்த வார்த்தையைச் சொல்லுங்கள்: "நண்பன்"', expectedAnswer: 'நண்பன்' }, te: { text: 'ఈ పదం చెప్పండి: "స్నేహితుడు"', expectedAnswer: 'స్నేహితుడు' } } },
    { id: 8, text: 'Read: "We play in the park"', expectedAnswer: 'we play in the park', type: 'sentence', translations: { en: { text: 'Read: "We play in the park"', expectedAnswer: 'we play in the park' }, hi: { text: 'पढ़ो: "हम पार्क में खेलते हैं"', expectedAnswer: 'हम पार्क में खेलते हैं' }, pa: { text: 'ਪੜ੍ਹੋ: "ਅਸੀਂ ਪਾਰਕ ਵਿੱਚ ਖੇਡਦੇ ਹਾਂ"', expectedAnswer: 'ਅਸੀਂ ਪਾਰਕ ਵਿੱਚ ਖੇਡਦੇ ਹਾਂ' }, ta: { text: 'படிக்கவும்: "நாங்கள் பூங்காவில் விளையாடுகிறோம்"', expectedAnswer: 'நாங்கள் பூங்காவில் விளையாடுகிறோம்' }, te: { text: 'చదవండి: "మేము పార్కులో ఆడతాము"', expectedAnswer: 'మేము పార్కులో ఆడతాము' } } },
  ],
  3: [
    { id: 1, text: 'Say the word: "BUTTERFLY"', expectedAnswer: 'butterfly', type: 'word', translations: { en: { text: 'Say the word: "BUTTERFLY"', expectedAnswer: 'butterfly' }, hi: { text: 'यह शब्द बोलो: "तितली"', expectedAnswer: 'तितली' }, pa: { text: 'ਇਹ ਸ਼ਬਦ ਬੋਲੋ: "ਤਿਤਲੀ"', expectedAnswer: 'ਤਿਤਲੀ' }, ta: { text: 'இந்த வார்த்தையைச் சொல்லுங்கள்: "பட்டாம்பூச்சி"', expectedAnswer: 'பட்டாம்பூச்சி' }, te: { text: 'ఈ పదం చెప్పండి: "సీతాకోకచిలుక"', expectedAnswer: 'సీతాకోకచిలుక' } } },
    { id: 2, text: 'Say the word: "ELEPHANT"', expectedAnswer: 'elephant', type: 'word', translations: { en: { text: 'Say the word: "ELEPHANT"', expectedAnswer: 'elephant' }, hi: { text: 'यह शब्द बोलो: "हाथी"', expectedAnswer: 'हाथी' }, pa: { text: 'ਇਹ ਸ਼ਬਦ ਬੋਲੋ: "ਹਾਥੀ"', expectedAnswer: 'ਹਾਥੀ' }, ta: { text: 'இந்த வார்த்தையைச் சொல்லுங்கள்: "யானை"', expectedAnswer: 'யானை' }, te: { text: 'ఈ పదం చెప్పండి: "ఏనుగు"', expectedAnswer: 'ఏనుగు' } } },
    { id: 3, text: 'Say the sounds in "STREAM"', expectedAnswer: 's t r e a m', type: 'phoneme', translations: { en: { text: 'Say the sounds in "STREAM"', expectedAnswer: 's t r e a m' }, hi: { text: '"नदी" में ध्वनियाँ बोलो', expectedAnswer: 'न दी' }, pa: { text: '"ਨਦੀ" ਵਿੱਚ ਆਵਾਜ਼ਾਂ ਬੋਲੋ', expectedAnswer: 'ਨ ਦੀ' }, ta: { text: '"ஓடை" என்பதில் ஒலிகளைச் சொல்லுங்கள்', expectedAnswer: 'ஓ டை' }, te: { text: '"వాగు" లో ధ్వనులు చెప్పండి', expectedAnswer: 'వా గు' } } },
    { id: 4, text: 'Read: "The quick brown fox jumps"', expectedAnswer: 'the quick brown fox jumps', type: 'sentence', translations: { en: { text: 'Read: "The quick brown fox jumps"', expectedAnswer: 'the quick brown fox jumps' }, hi: { text: 'पढ़ो: "तेज भूरी लोमड़ी कूदती है"', expectedAnswer: 'तेज भूरी लोमड़ी कूदती है' }, pa: { text: 'ਪੜ੍ਹੋ: "ਤੇਜ਼ ਭੂਰੀ ਲੂੰਬੜੀ ਛਾਲ ਮਾਰਦੀ ਹੈ"', expectedAnswer: 'ਤੇਜ਼ ਭੂਰੀ ਲੂੰਬੜੀ ਛਾਲ ਮਾਰਦੀ ਹੈ' }, ta: { text: 'படிக்கவும்: "வேகமான பழுப்பு நரி குதிக்கிறது"', expectedAnswer: 'வேகமான பழுப்பு நரி குதிக்கிறது' }, te: { text: 'చదవండి: "వేగవంతమైన గోధుమ నక్క దూకుతుంది"', expectedAnswer: 'వేగవంతమైన గోధుమ నక్క దూకుతుంది' } } },
    { id: 5, text: 'Say the word: "CHOCOLATE"', expectedAnswer: 'chocolate', type: 'word', translations: { en: { text: 'Say the word: "CHOCOLATE"', expectedAnswer: 'chocolate' }, hi: { text: 'यह शब्द बोलो: "चॉकलेट"', expectedAnswer: 'चॉकलेट' }, pa: { text: 'ਇਹ ਸ਼ਬਦ ਬੋਲੋ: "ਚਾਕਲੇਟ"', expectedAnswer: 'ਚਾਕਲੇਟ' }, ta: { text: 'இந்த வார்த்தையைச் சொல்லுங்கள்: "சாக்லேட்"', expectedAnswer: 'சாக்லேட்' }, te: { text: 'ఈ పదం చెప్పండి: "చాక్లెట్"', expectedAnswer: 'చాక్లెట్' } } },
    { id: 6, text: 'Say these letters: B, D, P, Q', expectedAnswer: 'b d p q', type: 'phoneme', translations: { en: { text: 'Say these letters: B, D, P, Q', expectedAnswer: 'b d p q' }, hi: { text: 'ये अक्षर बोलो: ब, द, प, क', expectedAnswer: 'ब द प क' }, pa: { text: 'ਇਹ ਅੱਖਰ ਬੋਲੋ: ਬ, ਦ, ਪ, ਕ', expectedAnswer: 'ਬ ਦ ਪ ਕ' }, ta: { text: 'இந்த எழுத்துகளைச் சொல்லுங்கள்: ப, ட, ப, க', expectedAnswer: 'ப ட ப க' }, te: { text: 'ఈ అక్షరాలు చెప్పండి: బ, ద, ప, క', expectedAnswer: 'బ ద ప క' } } },
    { id: 7, text: 'Say the word: "BEAUTIFUL"', expectedAnswer: 'beautiful', type: 'word', translations: { en: { text: 'Say the word: "BEAUTIFUL"', expectedAnswer: 'beautiful' }, hi: { text: 'यह शब्द बोलो: "सुंदर"', expectedAnswer: 'सुंदर' }, pa: { text: 'ਇਹ ਸ਼ਬਦ ਬੋਲੋ: "ਸੁੰਦਰ"', expectedAnswer: 'ਸੁੰਦਰ' }, ta: { text: 'இந்த வார்த்தையைச் சொல்லுங்கள்: "அழகான"', expectedAnswer: 'அழகான' }, te: { text: 'ఈ పదం చెప్పండి: "అందమైన"', expectedAnswer: 'అందమైన' } } },
    { id: 8, text: 'Read: "She went to the library yesterday"', expectedAnswer: 'she went to the library yesterday', type: 'sentence', translations: { en: { text: 'Read: "She went to the library yesterday"', expectedAnswer: 'she went to the library yesterday' }, hi: { text: 'पढ़ो: "वह कल पुस्तकालय गई"', expectedAnswer: 'वह कल पुस्तकालय गई' }, pa: { text: 'ਪੜ੍ਹੋ: "ਉਹ ਕੱਲ੍ਹ ਲਾਇਬ੍ਰੇਰੀ ਗਈ"', expectedAnswer: 'ਉਹ ਕੱਲ੍ਹ ਲਾਇਬ੍ਰੇਰੀ ਗਈ' }, ta: { text: 'படிக்கவும்: "அவள் நேற்று நூலகத்திற்குச் சென்றாள்"', expectedAnswer: 'அவள் நேற்று நூலகத்திற்குச் சென்றாள்' }, te: { text: 'చదవండి: "ఆమె నిన్న లైబ్రరీకి వెళ్ళింది"', expectedAnswer: 'ఆమె నిన్న లైబ్రరీకి వెళ్ళింది' } } },
  ],
};

// Translated dyscalculia questions
const dyscalculiaQuestionsTranslated: Record<number, TranslatedQuestion[]> = {
  1: [
    { id: 1, text: 'Count from 1 to 10', expectedAnswer: '1 2 3 4 5 6 7 8 9 10', type: 'number', translations: { en: { text: 'Count from 1 to 10', expectedAnswer: '1 2 3 4 5 6 7 8 9 10' }, hi: { text: '१ से १० तक गिनो', expectedAnswer: 'एक दो तीन चार पांच छह सात आठ नौ दस' }, pa: { text: '੧ ਤੋਂ ੧੦ ਤੱਕ ਗਿਣੋ', expectedAnswer: 'ਇੱਕ ਦੋ ਤਿੰਨ ਚਾਰ ਪੰਜ ਛੇ ਸੱਤ ਅੱਠ ਨੌਂ ਦਸ' }, ta: { text: '௧ முதல் ௧௦ வரை எண்ணுங்கள்', expectedAnswer: 'ஒன்று இரண்டு மூன்று நான்கு ஐந்து ஆறு ஏழு எட்டு ஒன்பது பத்து' }, te: { text: '౧ నుండి ౧౦ వరకు లెక్కించండి', expectedAnswer: 'ఒకటి రెండు మూడు నాలుగు ఐదు ఆరు ఏడు ఎనిమిది తొమ్మిది పది' } } },
    { id: 2, text: 'What is 2 + 1?', expectedAnswer: '3', type: 'calculation', translations: { en: { text: 'What is 2 + 1?', expectedAnswer: '3' }, hi: { text: '२ + १ = ?', expectedAnswer: 'तीन' }, pa: { text: '੨ + ੧ = ?', expectedAnswer: 'ਤਿੰਨ' }, ta: { text: '௨ + ௧ = ?', expectedAnswer: 'மூன்று' }, te: { text: '౨ + ౧ = ?', expectedAnswer: 'మూడు' } } },
    { id: 3, text: 'What is 3 - 1?', expectedAnswer: '2', type: 'calculation', translations: { en: { text: 'What is 3 - 1?', expectedAnswer: '2' }, hi: { text: '३ - १ = ?', expectedAnswer: 'दो' }, pa: { text: '੩ - ੧ = ?', expectedAnswer: 'ਦੋ' }, ta: { text: '௩ - ௧ = ?', expectedAnswer: 'இரண்டு' }, te: { text: '౩ - ౧ = ?', expectedAnswer: 'రెండు' } } },
    { id: 4, text: 'What number comes after 5?', expectedAnswer: '6', type: 'number', translations: { en: { text: 'What number comes after 5?', expectedAnswer: '6' }, hi: { text: '५ के बाद कौन सी संख्या आती है?', expectedAnswer: 'छह' }, pa: { text: '੫ ਤੋਂ ਬਾਅਦ ਕਿਹੜਾ ਨੰਬਰ ਆਉਂਦਾ ਹੈ?', expectedAnswer: 'ਛੇ' }, ta: { text: '௫ க்குப் பிறகு என்ன எண் வரும்?', expectedAnswer: 'ஆறு' }, te: { text: '౫ తర్వాత ఏ సంఖ్య వస్తుంది?', expectedAnswer: 'ఆరు' } } },
    { id: 5, text: 'How many fingers do you have?', expectedAnswer: '10', type: 'number', translations: { en: { text: 'How many fingers do you have?', expectedAnswer: '10' }, hi: { text: 'तुम्हारी कितनी उंगलियां हैं?', expectedAnswer: 'दस' }, pa: { text: 'ਤੁਹਾਡੀਆਂ ਕਿੰਨੀਆਂ ਉਂਗਲਾਂ ਹਨ?', expectedAnswer: 'ਦਸ' }, ta: { text: 'உங்களுக்கு எத்தனை விரல்கள் உள்ளன?', expectedAnswer: 'பத்து' }, te: { text: 'మీకు ఎన్ని వేళ్ళు ఉన్నాయి?', expectedAnswer: 'పది' } } },
    { id: 6, text: 'What is 1 + 1?', expectedAnswer: '2', type: 'calculation', translations: { en: { text: 'What is 1 + 1?', expectedAnswer: '2' }, hi: { text: '१ + १ = ?', expectedAnswer: 'दो' }, pa: { text: '੧ + ੧ = ?', expectedAnswer: 'ਦੋ' }, ta: { text: '௧ + ௧ = ?', expectedAnswer: 'இரண்டு' }, te: { text: '౧ + ౧ = ?', expectedAnswer: 'రెండు' } } },
    { id: 7, text: 'Count backwards from 5 to 1', expectedAnswer: '5 4 3 2 1', type: 'number', translations: { en: { text: 'Count backwards from 5 to 1', expectedAnswer: '5 4 3 2 1' }, hi: { text: '५ से १ तक उल्टा गिनो', expectedAnswer: 'पांच चार तीन दो एक' }, pa: { text: '੫ ਤੋਂ ੧ ਤੱਕ ਉਲਟਾ ਗਿਣੋ', expectedAnswer: 'ਪੰਜ ਚਾਰ ਤਿੰਨ ਦੋ ਇੱਕ' }, ta: { text: '௫ இலிருந்து ௧ வரை பின்னோக்கி எண்ணுங்கள்', expectedAnswer: 'ஐந்து நான்கு மூன்று இரண்டு ஒன்று' }, te: { text: '౫ నుండి ౧ వరకు వెనక్కి లెక్కించండి', expectedAnswer: 'ఐదు నాలుగు మూడు రెండు ఒకటి' } } },
    { id: 8, text: 'What is 4 + 1?', expectedAnswer: '5', type: 'calculation', translations: { en: { text: 'What is 4 + 1?', expectedAnswer: '5' }, hi: { text: '४ + १ = ?', expectedAnswer: 'पांच' }, pa: { text: '੪ + ੧ = ?', expectedAnswer: 'ਪੰਜ' }, ta: { text: '௪ + ௧ = ?', expectedAnswer: 'ஐந்து' }, te: { text: '౪ + ౧ = ?', expectedAnswer: 'ఐదు' } } },
  ],
  2: [
    { id: 1, text: 'Count from 1 to 20', expectedAnswer: '1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20', type: 'number', translations: { en: { text: 'Count from 1 to 20', expectedAnswer: '1 to 20' }, hi: { text: '१ से २० तक गिनो', expectedAnswer: 'एक से बीस तक' }, pa: { text: '੧ ਤੋਂ ੨੦ ਤੱਕ ਗਿਣੋ', expectedAnswer: 'ਇੱਕ ਤੋਂ ਵੀਹ ਤੱਕ' }, ta: { text: '௧ முதல் ௨௦ வரை எண்ணுங்கள்', expectedAnswer: 'ஒன்று முதல் இருபது வரை' }, te: { text: '౧ నుండి ౨౦ వరకు లెక్కించండి', expectedAnswer: 'ఒకటి నుండి ఇరవై వరకు' } } },
    { id: 2, text: 'What is 5 + 3?', expectedAnswer: '8', type: 'calculation', translations: { en: { text: 'What is 5 + 3?', expectedAnswer: '8' }, hi: { text: '५ + ३ = ?', expectedAnswer: 'आठ' }, pa: { text: '੫ + ੩ = ?', expectedAnswer: 'ਅੱਠ' }, ta: { text: '௫ + ௩ = ?', expectedAnswer: 'எட்டு' }, te: { text: '౫ + ౩ = ?', expectedAnswer: 'ఎనిమిది' } } },
    { id: 3, text: 'What is 10 - 4?', expectedAnswer: '6', type: 'calculation', translations: { en: { text: 'What is 10 - 4?', expectedAnswer: '6' }, hi: { text: '१० - ४ = ?', expectedAnswer: 'छह' }, pa: { text: '੧੦ - ੪ = ?', expectedAnswer: 'ਛੇ' }, ta: { text: '௧௦ - ௪ = ?', expectedAnswer: 'ஆறு' }, te: { text: '౧౦ - ౪ = ?', expectedAnswer: 'ఆరు' } } },
    { id: 4, text: 'Count backwards from 10 to 1', expectedAnswer: '10 9 8 7 6 5 4 3 2 1', type: 'number', translations: { en: { text: 'Count backwards from 10 to 1', expectedAnswer: '10 to 1' }, hi: { text: '१० से १ तक उल्टा गिनो', expectedAnswer: 'दस से एक तक' }, pa: { text: '੧੦ ਤੋਂ ੧ ਤੱਕ ਉਲਟਾ ਗਿਣੋ', expectedAnswer: 'ਦਸ ਤੋਂ ਇੱਕ ਤੱਕ' }, ta: { text: '௧௦ இலிருந்து ௧ வரை பின்னோக்கி எண்ணுங்கள்', expectedAnswer: 'பத்து முதல் ஒன்று வரை' }, te: { text: '౧౦ నుండి ౧ వరకు వెనక్కి లెక్కించండి', expectedAnswer: 'పది నుండి ఒకటి వరకు' } } },
    { id: 5, text: 'What is 2 + 7?', expectedAnswer: '9', type: 'calculation', translations: { en: { text: 'What is 2 + 7?', expectedAnswer: '9' }, hi: { text: '२ + ७ = ?', expectedAnswer: 'नौ' }, pa: { text: '੨ + ੭ = ?', expectedAnswer: 'ਨੌਂ' }, ta: { text: '௨ + ௭ = ?', expectedAnswer: 'ஒன்பது' }, te: { text: '౨ + ౭ = ?', expectedAnswer: 'తొమ్మిది' } } },
    { id: 6, text: 'What number comes after 15?', expectedAnswer: '16', type: 'number', translations: { en: { text: 'What number comes after 15?', expectedAnswer: '16' }, hi: { text: '१५ के बाद कौन सी संख्या आती है?', expectedAnswer: 'सोलह' }, pa: { text: '੧੫ ਤੋਂ ਬਾਅਦ ਕਿਹੜਾ ਨੰਬਰ ਆਉਂਦਾ ਹੈ?', expectedAnswer: 'ਸੋਲਾਂ' }, ta: { text: '௧௫ க்குப் பிறகு என்ன எண் வரும்?', expectedAnswer: 'பதினாறு' }, te: { text: '౧౫ తర్వాత ఏ సంఖ్య వస్తుంది?', expectedAnswer: 'పదహారు' } } },
    { id: 7, text: 'What is 8 - 3?', expectedAnswer: '5', type: 'calculation', translations: { en: { text: 'What is 8 - 3?', expectedAnswer: '5' }, hi: { text: '८ - ३ = ?', expectedAnswer: 'पांच' }, pa: { text: '੮ - ੩ = ?', expectedAnswer: 'ਪੰਜ' }, ta: { text: '௮ - ௩ = ?', expectedAnswer: 'ஐந்து' }, te: { text: '౮ - ౩ = ?', expectedAnswer: 'ఐదు' } } },
    { id: 8, text: 'Skip count by 2s: 2, 4, 6...', expectedAnswer: '2 4 6 8 10', type: 'number', translations: { en: { text: 'Skip count by 2s: 2, 4, 6...', expectedAnswer: '2 4 6 8 10' }, hi: { text: '२ की गिनती करो: २, ४, ६...', expectedAnswer: 'दो चार छह आठ दस' }, pa: { text: '੨ ਦੀ ਗਿਣਤੀ ਕਰੋ: ੨, ੪, ੬...', expectedAnswer: 'ਦੋ ਚਾਰ ਛੇ ਅੱਠ ਦਸ' }, ta: { text: '௨ என்று எண்ணுங்கள்: ௨, ௪, ௬...', expectedAnswer: 'இரண்டு நான்கு ஆறு எட்டு பத்து' }, te: { text: '౨ల లెక్కింపు: ౨, ౪, ౬...', expectedAnswer: 'రెండు నాలుగు ఆరు ఎనిమిది పది' } } },
  ],
  3: [
    { id: 1, text: 'What is 12 + 15?', expectedAnswer: '27', type: 'calculation', translations: { en: { text: 'What is 12 + 15?', expectedAnswer: '27' }, hi: { text: '१२ + १५ = ?', expectedAnswer: 'सत्ताईस' }, pa: { text: '੧੨ + ੧੫ = ?', expectedAnswer: 'ਸਤਾਈ' }, ta: { text: '௧௨ + ௧௫ = ?', expectedAnswer: 'இருபத்தேழு' }, te: { text: '౧౨ + ౧౫ = ?', expectedAnswer: 'ఇరవై ఏడు' } } },
    { id: 2, text: 'What is 25 - 13?', expectedAnswer: '12', type: 'calculation', translations: { en: { text: 'What is 25 - 13?', expectedAnswer: '12' }, hi: { text: '२५ - १३ = ?', expectedAnswer: 'बारह' }, pa: { text: '੨੫ - ੧੩ = ?', expectedAnswer: 'ਬਾਰਾਂ' }, ta: { text: '௨௫ - ௧௩ = ?', expectedAnswer: 'பன்னிரண்டு' }, te: { text: '౨౫ - ౧౩ = ?', expectedAnswer: 'పన్నెండు' } } },
    { id: 3, text: 'What is 3 × 4?', expectedAnswer: '12', type: 'calculation', translations: { en: { text: 'What is 3 × 4?', expectedAnswer: '12' }, hi: { text: '३ × ४ = ?', expectedAnswer: 'बारह' }, pa: { text: '੩ × ੪ = ?', expectedAnswer: 'ਬਾਰਾਂ' }, ta: { text: '௩ × ௪ = ?', expectedAnswer: 'பன்னிரண்டு' }, te: { text: '౩ × ౪ = ?', expectedAnswer: 'పన్నెండు' } } },
    { id: 4, text: 'Count by 5s from 5 to 50', expectedAnswer: '5 10 15 20 25 30 35 40 45 50', type: 'number', translations: { en: { text: 'Count by 5s from 5 to 50', expectedAnswer: '5 to 50 by 5s' }, hi: { text: '५ से ५० तक ५ की गिनती करो', expectedAnswer: 'पांच से पचास तक' }, pa: { text: '੫ ਤੋਂ ੫੦ ਤੱਕ ੫ ਦੀ ਗਿਣਤੀ ਕਰੋ', expectedAnswer: 'ਪੰਜ ਤੋਂ ਪੰਜਾਹ ਤੱਕ' }, ta: { text: '௫ முதல் ௫௦ வரை ௫ என்று எண்ணுங்கள்', expectedAnswer: 'ஐந்து முதல் ஐம்பது வரை' }, te: { text: '౫ నుండి ౫౦ వరకు ౫ల లెక్కింపు', expectedAnswer: 'ఐదు నుండి యాభై వరకు' } } },
    { id: 5, text: 'What is 6 × 7?', expectedAnswer: '42', type: 'calculation', translations: { en: { text: 'What is 6 × 7?', expectedAnswer: '42' }, hi: { text: '६ × ७ = ?', expectedAnswer: 'बयालीस' }, pa: { text: '੬ × ੭ = ?', expectedAnswer: 'ਬਿਆਲੀ' }, ta: { text: '௬ × ௭ = ?', expectedAnswer: 'நாற்பத்திரண்டு' }, te: { text: '౬ × ౭ = ?', expectedAnswer: 'నలభై రెండు' } } },
    { id: 6, text: 'What is 100 - 45?', expectedAnswer: '55', type: 'calculation', translations: { en: { text: 'What is 100 - 45?', expectedAnswer: '55' }, hi: { text: '१०० - ४५ = ?', expectedAnswer: 'पचपन' }, pa: { text: '੧੦੦ - ੪੫ = ?', expectedAnswer: 'ਪੰਜਾਹ ਪੰਜ' }, ta: { text: '௧௦௦ - ௪௫ = ?', expectedAnswer: 'ஐம்பத்தைந்து' }, te: { text: '౧౦౦ - ౪౫ = ?', expectedAnswer: 'యాభై ఐదు' } } },
    { id: 7, text: 'What is 8 × 5?', expectedAnswer: '40', type: 'calculation', translations: { en: { text: 'What is 8 × 5?', expectedAnswer: '40' }, hi: { text: '८ × ५ = ?', expectedAnswer: 'चालीस' }, pa: { text: '੮ × ੫ = ?', expectedAnswer: 'ਚਾਲੀ' }, ta: { text: '௮ × ௫ = ?', expectedAnswer: 'நாற்பது' }, te: { text: '౮ × ౫ = ?', expectedAnswer: 'నలభై' } } },
    { id: 8, text: 'What is 12 ÷ 4?', expectedAnswer: '3', type: 'calculation', translations: { en: { text: 'What is 12 ÷ 4?', expectedAnswer: '3' }, hi: { text: '१२ ÷ ४ = ?', expectedAnswer: 'तीन' }, pa: { text: '੧੨ ÷ ੪ = ?', expectedAnswer: 'ਤਿੰਨ' }, ta: { text: '௧௨ ÷ ௪ = ?', expectedAnswer: 'மூன்று' }, te: { text: '౧౨ ÷ ౪ = ?', expectedAnswer: 'మూడు' } } },
  ],
};

// Function to get translated questions
export function getTranslatedQuestions(
  grade: number, 
  sessionType: 'dyslexia' | 'dyscalculia',
  language: Language
): Question[] {
  const gradeNum = Math.max(1, Math.min(3, grade)); // Translations available for grades 1-3
  
  if (language === 'en' || grade > 3) {
    // For English or higher grades, use original questions
    return [];
  }
  
  const questionBank = sessionType === 'dyslexia' 
    ? dyslexiaQuestionsHindi 
    : dyscalculiaQuestionsTranslated;
  
  const questions = questionBank[gradeNum];
  
  if (!questions) return [];
  
  // Transform to simple Question format with translated text
  return questions.map(q => ({
    id: q.id,
    text: q.translations[language]?.text || q.text,
    expectedAnswer: q.translations[language]?.expectedAnswer || q.expectedAnswer,
    type: q.type,
  }));
}

// Check if translations are available for given grade and language
export function hasTranslations(grade: number, language: Language): boolean {
  return language !== 'en' && grade <= 3;
}
